/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SecureFormAnswerCreateNestedManyWithoutSecureFormsInput } from "./SecureFormAnswerCreateNestedManyWithoutSecureFormsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
@InputType()
class SecureFormCreateInput {
  @ApiProperty({
    required: false,
    type: () => SecureFormAnswerCreateNestedManyWithoutSecureFormsInput,
  })
  @ValidateNested()
  @Type(() => SecureFormAnswerCreateNestedManyWithoutSecureFormsInput)
  @IsOptional()
  @Field(() => SecureFormAnswerCreateNestedManyWithoutSecureFormsInput, {
    nullable: true,
  })
  answers?: SecureFormAnswerCreateNestedManyWithoutSecureFormsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  privateKey?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  publicKey?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  structure?: string | null;
}
export { SecureFormCreateInput };
